(seq  listredis (dcreate ))
(print (rpush listredis 'rosslyn 'socket))
(print (rpush listredis 'rosslyn 'woshishui))
(print (rpush listredis 'rosslyn 'socket))
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))
(print  '@@@@@@@@@@@@@@@)
(rpush listredis 'rosslyn 'socket))
(print (rpush listredis 'rosslyn 'woshishui))
(print (rpush listredis 'rosslyn 'socket))
(lrem listredis 'rosslyn 'socket)
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))
(print  '@@@@@)
(rpush listredis 'rosslyn 1))
(print (rpush listredis 'rosslyn 1))
(print (rpush listredis 'rosslyn 'abc))
(print (rpush listredis 'rosslyn 2))
(lrem listredis 'rosslyn 'abc)
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))
(print (lpop  listredis 'rosslyn))

